import re


SHORT_URL_MIN_EXPIRE_DAYS = 1
SHORT_URL_MAX_EXPIRE_DAYS = 365
SHORT_URL_DEFAULT_EXPIRE_DAYS = 1

MAX_URL_LENGTH = 2048
SHORT_KEY_MAX_LENGTH = 15
SHORT_KEY_LENGTH = 12
TOKEN_BYTES = 8

MAX_SHORT_KEY_GENERATION_ATTEMPTS = 10
SHORT_KEY_ALPHABET = "1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
SHORT_KEY_REGEX = r"^[" + re.escape(SHORT_KEY_ALPHABET) + "]+$"
