# Generated by Django 5.2.1 on 2025-05-30 15:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator()])),
                ('short_key', models.CharField(db_index=True, max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 5, 31, 15, 15, 35, 522489, tzinfo=datetime.timezone.utc))),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='short_urls.shorturl')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['-clicked_at'], name='short_urls__clicked_62d71d_idx')],
            },
        ),
    ]
