# Generated by Django 5.2 on 2025-06-01 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Original long URL to be shortened', max_length=2048, validators=[django.core.validators.URLValidator()])),
                ('short_key', models.CharField(db_index=True, help_text='Unique key for the shortened URL', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the URL was shortened')),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp for the shortened URL')),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating if the URL is active')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the click occurred')),
                ('short_url', models.ForeignKey(help_text='Associated shortened URL', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='short_urls.shorturl')),
            ],
            options={
                'verbose_name': 'URL Click',
                'verbose_name_plural': 'URL Clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['-clicked_at'], name='short_urls__clicked_62d71d_idx')],
            },
        ),
    ]
