# Generated by Django 5.2.1 on 2025-05-30 15:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 15, 51, 27, 82049, tzinfo=datetime.timezone.utc)),
        ),
    ]
