# Generated by Django 5.2 on 2025-05-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0003_remove_shorturl_click_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='user',
        ),
    ]
