# Generated by Django 5.2 on 2025-06-01 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0004_remove_shorturl_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'URL Click', 'verbose_name_plural': 'URL Clicks'},
        ),
        migrations.AlterField(
            model_name='click',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the click occurred'),
        ),
        migrations.AlterField(
            model_name='click',
            name='short_url',
            field=models.ForeignKey(help_text='Associated shortened URL', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='short_urls.shorturl'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the URL was shortened'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(help_text='Expiration timestamp for the shortened URL'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating if the URL is active'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(help_text='Original long URL to be shortened', max_length=2048, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_key',
            field=models.CharField(db_index=True, help_text='Unique key for the shortened URL', max_length=15, unique=True),
        ),
    ]
